### ISSUE TITLE
Deprecated attributes do not work for definition and lemma

### ISSUE THREAD

**Issue by Alizter** [liyishuai/coq-json#3]
Hello, it looks like you are using the deprecated attribute for definitions and lemmas in various places (Operator.v), This doesn't actually do anything and should instead by achieved by defining a notation with the old name and deprecating that instead.

See https://github.com/coq/coq/pull/15760

**Comment by liyishuai** [comment]
Should I do this?
```coq
Definition deprecated_foo := ...
#[deprecated(since="8.14",note="Use bar instead.")]
Notation foo := deprecated_foo.
```

**Comment by Alizter** [comment]
Yep

**Comment by jjhugues** [comment]
See the following documentation as a guideline: https://coq.github.io/doc/master/refman/using/libraries/writing.html?highlight=deprecated#coq:attr.deprecated
