### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by alpaylan** [liyishuai/coq-json#5]
I am trying to use the library for JSON parsing but I could not really find any usage examples. Could you add some examples please?

**Comment by liyishuai** [comment]
In the bottom of `Lexer.v` you can find a `from_string` function. Try playing with it before I get a computer tomorrow and add its usage. Sorry for the misleading code structure.

**Comment by alpaylan** [comment]
No problem! I managed to do it. I'm pushing a PR to the tests repo.

**Comment by alpaylan** [comment]
https://github.com/liyishuai/coq-json/pull/6

Done.
