### ISSUE TITLE
`coq-ceres` is Not a Dependency in `coq-json.opam`

### ISSUE THREAD

**Issue by zachary-kent** [liyishuai/coq-json#7]
Title. This issue surfaced when building my project depending on `coq-json` and I received the error `Error: Cannot load Ceres.CeresString: no physical path bound to Ceres` after upgrading to 0.8 dune coq integration. Thanks!

**Comment by liyishuai** [comment]
`coq-json` depends on `coq-parsec` that depends on `coq-ceres`. Do you have `coq-parsec` installed?

**Comment by liyishuai** [comment]
Propose closing as completed, if no concerns arise this week.
